name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Security Check
        run: |
          if [ -f .env ] || [ -f AssistWakeWordSniffer/.env ]; then
            echo "ERROR: .env file detected!"
            exit 1
          fi

      - name: Set Lowercase Image Name
        run: |
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # This tells Docker to look inside your subfolder for the Dockerfile
          context: ./AssistWakeWordSniffer
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest